version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sustainability
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # This service runs the migrations and then exits.
  migrate:
    image: migrate/migrate:v4.15.2
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@postgres:5432/sustainability?sslmode=disable",
      "up"
    ]
    volumes:
      - ./internal/migration:/migrations
    depends_on:
      - postgres

  user-service:
    build: .
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/sustainability?sslmode=disable"
      JWT_SECRET: "your_jwt_secret"
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - migrate

volumes:
  pgdata: